(() => {
  const $ = id => document.getElementById(id), root = document.querySelector('.app');
  const meta = {doodle:['🛸 Doodle Jump','Наклоняйте телефон'],snake:['🐍 Змейка','Свайпы или стрелки'],flappy:['🐤 Flappy','Касайтесь экрана'],breakout:['🧱 Арканоид','Ведите платформу'],merge:['🔢 2048','Свайпы или стрелки'],memory:['🧠 Мемори','Найдите все пары'],tictac:['⭕ Крестики-нолики','Вы играете крестиками']};
  let game=null, raf=0, cleanup=()=>{}, score=0, best=0, touch=null, timeLeft=180, timer=0, rewarded=false;
  const LIMIT=15,HOUR=3600000;
  const wallet=()=>{let w;try{w=JSON.parse(localStorage.getItem('mini_games_wallet'))}catch{}if(!w||Date.now()-w.since>=HOUR)w={coins:w?.coins||0,used:0,since:Date.now()};return w};
  const saveWallet=w=>{localStorage.setItem('mini_games_wallet',JSON.stringify(w));renderWallet()};
  function renderWallet(){const w=wallet(),left=Math.max(0,LIMIT-w.used);$('coinBalance').textContent=`🪙 ${w.coins}`;$('gamesLeft').textContent=`${left} из ${LIMIT} игр`;$('arcadeWallet')&&($('arcadeWallet').textContent=`🪙 ${w.coins} · ${left} игр`)}
  function charge(){const w=wallet();if(w.used<LIMIT)w.used++;else if(w.coins)w.coins--;else return false;saveWallet(w);return true}
  function reward(){if(rewarded)return;rewarded=true;const w=wallet();w.coins++;saveWallet(w)}
  const shell=document.createElement('main'); shell.id='arcadeScreen'; shell.className='arcade-screen hidden';
  shell.innerHTML=`<section class="arcade-head card"><div><h2 id="arcadeTitle"></h2><small id="arcadeSub"></small></div><div class="arcade-score"><strong id="arcadeScore">0</strong><small id="arcadeBest">Рекорд: 0</small></div></section><p class="economy-note"><span id="arcadeWallet"></span> · <span id="arcadeTime" class="arcade-time">03:00</span></p><section id="arcadeStage" class="arcade-stage"></section><p id="arcadeTip" class="arcade-tip"></p><section class="arcade-controls card"><button id="arcadeRestart">Заново</button><button id="arcadeExtend">+60 сек · 🪙 1</button><button id="arcadeGyro" class="gyro-btn hidden">Включить наклон</button><button id="arcadeBack">К играм</button></section>`;
  root.insertBefore(shell,$('toast'));
  const hideAll=()=>['homeScreen','modeScreen','levelScreen','onlineScreen','gameScreen','extraGameScreen'].forEach(id=>$(id)?.classList.add('hidden'));
  function setScore(v){score=v;$('arcadeScore').textContent=v;if(v>best){best=v;localStorage.setItem(`arcade_best_${game}`,v)}$('arcadeBest').textContent=`Рекорд: ${best}`}
  function open(type){stop();game=type;best=Number(localStorage.getItem(`arcade_best_${type}`)||0);hideAll();shell.classList.remove('hidden');$('arcadeTitle').textContent=meta[type][0];$('arcadeSub').textContent=meta[type][1];$('arcadeTip').textContent=type==='doodle'?'Разрешите датчики и наклоняйте телефон. Также работают касания слева/справа и стрелки.':'Свайпы и касания работают прямо на игровом поле.';$('arcadeGyro').classList.toggle('hidden',type!=='doodle');start()}
  function stop(){cancelAnimationFrame(raf);clearInterval(timer);raf=0;cleanup();cleanup=()=>{};$('arcadeStage').replaceChildren()}
  function home(){stop();shell.classList.add('hidden');$('homeScreen').classList.remove('hidden');game=null}
  function start(){if(!charge()){overlay('Лимит исчерпан','15 бесплатных игр использованы, а монет на новую игру нет.');return}const type=game;stop();game=type;rewarded=false;timeLeft=180;setScore(0);renderWallet();tick();timer=setInterval(()=>{timeLeft--;tick();if(timeLeft<=0){stop();overlay('Время вышло','Продлите игру за 1 монету или начните заново.')}},1000);({doodle, snake, flappy, breakout, merge, memory, tictac}[game])()}
  function tick(){$('arcadeTime').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(timeLeft%60).padStart(2,'0')}`}
  document.querySelectorAll('[data-arcade]').forEach(b=>b.onclick=()=>open(b.dataset.arcade));$('arcadeRestart').onclick=start;$('arcadeExtend').onclick=()=>{const w=wallet();if(!w.coins)return $('arcadeTip').textContent='Недостаточно монет';w.coins--;saveWallet(w);timeLeft+=60;tick()};$('arcadeBack').onclick=home;$('homeBtn').addEventListener('click',()=>{if(!shell.classList.contains('hidden'))home()});
  function canvas(){const c=document.createElement('canvas'),stage=$('arcadeStage'),dpr=Math.min(devicePixelRatio||1,2),w=360,h=480;c.width=w*dpr;c.height=h*dpr;stage.replaceChildren(c);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);return{c,ctx,w,h}}
  function overlay(title,text){clearInterval(timer);if(title==='Победа!'||title==='Все пары найдены!')reward();const o=document.createElement('div');o.className='arcade-overlay';o.innerHTML=`<div><h2>${title}</h2><p>${text}</p><button>Играть ещё</button></div>`;o.querySelector('button').onclick=start;$('arcadeStage').append(o)}
  function doodle(){const{c,ctx,w,h}=canvas();let p={x:165,y:390,vx:0,vy:-9},tilt=0,left=false,right=false,last=performance.now(),platforms=[{x:135,y:440,w:90}];for(let y=370;y>0;y-=65)platforms.push({x:Math.random()*270,y,w:70+Math.random()*35});
    const orient=e=>{if(e.gamma!=null)tilt=Math.max(-1,Math.min(1,e.gamma/22))};window.addEventListener('deviceorientation',orient);$('arcadeGyro').onclick=async()=>{try{if(typeof DeviceOrientationEvent?.requestPermission==='function'){if(await DeviceOrientationEvent.requestPermission()!=='granted')throw 0}window.addEventListener('deviceorientation',orient);$('arcadeGyro').textContent='Наклон включён ✓'}catch{$('arcadeTip').textContent='Доступ к датчику не получен — используйте касания или стрелки.'}};
    const key=e=>{if(e.key==='ArrowLeft')left=e.type==='keydown';if(e.key==='ArrowRight')right=e.type==='keydown'};addEventListener('keydown',key);addEventListener('keyup',key);const down=e=>{const x=e.touches?.[0].clientX??e.clientX,left=x<innerWidth/2;right=!left},up=()=>left=right=false;c.addEventListener('pointerdown',down);c.addEventListener('pointerup',up);
    function frame(t){const dt=Math.min(2,(t-last)/16.67);last=t;p.vx+=(tilt*0.55+(right?0.55:0)-(left?0.55:0))*dt;p.vx*=.91;p.x+=p.vx*dt;p.vy+=.36*dt;p.y+=p.vy*dt;if(p.x<-20)p.x=w;if(p.x>w)p.x=-20;if(p.vy>0)for(const q of platforms)if(p.y+32>=q.y&&p.y+32-p.vy*dt<q.y&&p.x+24>q.x&&p.x<q.x+q.w){p.vy=-10.4;break}if(p.y<190){const d=190-p.y;p.y=190;platforms.forEach(q=>q.y+=d);setScore(score+Math.round(d));platforms=platforms.filter(q=>q.y<h+20);while(platforms.length<9){const top=Math.min(...platforms.map(q=>q.y));platforms.push({x:Math.random()*275,y:top-55-Math.random()*30,w:65+Math.random()*35})}}draw();if(p.y>h+30)return overlay('Падение!',`Высота: ${score}`);raf=requestAnimationFrame(frame)}
    function draw(){ctx.fillStyle='#dff4ff';ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.8)';for(let i=0;i<16;i++)ctx.fillRect((i*79)%w,(i*113+score*.15)%h,3,3);for(const q of platforms){ctx.fillStyle='#36a852';ctx.fillRect(q.x,q.y,q.w,10);ctx.fillStyle='#176b34';ctx.fillRect(q.x,q.y+8,q.w,4)}ctx.fillStyle='#8b5cf6';ctx.fillRect(p.x,p.y,25,28);ctx.fillStyle='#fff';ctx.fillRect(p.x+5,p.y+6,5,5);ctx.fillRect(p.x+16,p.y+6,5,5);ctx.fillStyle='#222';ctx.fillRect(p.x+7,p.y+7,2,2);ctx.fillRect(p.x+18,p.y+7,2,2)}raf=requestAnimationFrame(frame);cleanup=()=>{removeEventListener('deviceorientation',orient);removeEventListener('keydown',key);removeEventListener('keyup',key)}}
  function snake(){const{c,ctx,w,h}=canvas(),n=18,s=w/n;let body=[[9,12],[8,12],[7,12]],dir=[1,0],next=dir,food=[13,7],last=0;const move=d=>{if(d[0]!==-dir[0]||d[1]!==-dir[1])next=d};const key=e=>({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key]&&move({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key]));addEventListener('keydown',key);swipes(c,move);function frame(t){if(t-last>125){last=t;dir=next;const q=[body[0][0]+dir[0],body[0][1]+dir[1]];if(q[0]<0||q[0]>=n||q[1]<0||q[1]>=24||body.some(v=>v[0]===q[0]&&v[1]===q[1]))return overlay('Игра окончена',`Яблок: ${score}`);body.unshift(q);if(q[0]===food[0]&&q[1]===food[1]){setScore(score+1);do food=[Math.floor(Math.random()*n),Math.floor(Math.random()*24)];while(body.some(v=>v[0]===food[0]&&v[1]===food[1]))}else body.pop()}ctx.fillStyle='#071b2a';ctx.fillRect(0,0,w,h);ctx.fillStyle='#ef4444';ctx.beginPath();ctx.arc((food[0]+.5)*s,(food[1]+.5)*s,s*.36,0,7);ctx.fill();body.forEach((v,i)=>{ctx.fillStyle=i?'#34d399':'#a7f3d0';ctx.fillRect(v[0]*s+1,v[1]*s+1,s-2,s-2)});raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);cleanup=()=>removeEventListener('keydown',key)}
  function flappy(){const{c,ctx,w,h}=canvas();let y=220,v=0,pipes=[],last=0,spawn=0,started=false;const flap=()=>{v=-6.6;started=true};c.onpointerdown=flap;const key=e=>{if(e.code==='Space'||e.key==='ArrowUp'){e.preventDefault();flap()}};addEventListener('keydown',key);function frame(t){const dt=Math.min(2,(t-last||16)/16);last=t;if(started){v+=.34*dt;y+=v*dt;spawn+=dt;if(spawn>95){spawn=0;pipes.push({x:w,g:90+Math.random()*230,passed:false})}pipes.forEach(p=>p.x-=2.6*dt);pipes=pipes.filter(p=>p.x>-60);for(const p of pipes){if(!p.passed&&p.x<80){p.passed=true;setScore(score+1)}if(80+22>p.x&&80-22<p.x+54&&(y-17<p.g-65||y+17>p.g+65))return overlay('Столкновение!',`Счёт: ${score}`)}if(y>h||y<0)return overlay('Падение!',`Счёт: ${score}`)}ctx.fillStyle='#70d6ed';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';pipes.forEach(p=>{ctx.fillStyle='#30a852';ctx.fillRect(p.x,0,54,p.g-65);ctx.fillRect(p.x,p.g+65,54,h)});ctx.fillStyle='#ffd43b';ctx.beginPath();ctx.arc(80,y,18,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(80,y-10,10,8);if(!started){ctx.fillStyle='#164e63';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.fillText('Коснитесь, чтобы взлететь',w/2,h/2)}raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);cleanup=()=>removeEventListener('keydown',key)}
  function breakout(){const{c,ctx,w,h}=canvas();let pad=145,ball={x:180,y:390,vx:3,vy:-4},bricks=[];for(let r=0;r<6;r++)for(let x=0;x<8;x++)bricks.push({x:8+x*44,y:45+r*24,on:true,c:r});const point=e=>{const r=c.getBoundingClientRect();pad=(e.clientX-r.left)/r.width*w-36};c.onpointermove=point;c.onpointerdown=point;function frame(){ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x<7||ball.x>w-7)ball.vx*=-1;if(ball.y<7)ball.vy*=-1;if(ball.y>h)return overlay('Мяч потерян',`Блоков: ${score}`);if(ball.y>430&&ball.y<445&&ball.x>pad&&ball.x<pad+72){ball.vy=-Math.abs(ball.vy);ball.vx+=(ball.x-(pad+36))*.035}for(const b of bricks)if(b.on&&ball.x>b.x&&ball.x<b.x+39&&ball.y>b.y&&ball.y<b.y+17){b.on=false;ball.vy*=-1;setScore(score+1);if(score===48)return overlay('Победа!','Все блоки разбиты')}ctx.fillStyle='#071525';ctx.fillRect(0,0,w,h);for(const b of bricks)if(b.on){ctx.fillStyle=`hsl(${b.c*44+330} 80% 62%)`;ctx.fillRect(b.x,b.y,39,17)}ctx.fillStyle='#e2e8f0';ctx.fillRect(pad,438,72,12);ctx.beginPath();ctx.arc(ball.x,ball.y,7,0,7);ctx.fill();raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame)}
  function swipes(el,fn){let p;el.addEventListener('pointerdown',e=>p=[e.clientX,e.clientY]);el.addEventListener('pointerup',e=>{if(!p)return;const dx=e.clientX-p[0],dy=e.clientY-p[1];if(Math.max(Math.abs(dx),Math.abs(dy))>18)fn(Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)]);p=null})}
  function merge(){const stage=$('arcadeStage'),grid=document.createElement('div');grid.className='arcade-dom merge-grid';stage.replaceChildren(grid);let a=Array(16).fill(0);const add=()=>{const z=a.map((v,i)=>v?null:i).filter(v=>v!=null);if(z.length)a[z[Math.floor(Math.random()*z.length)]]=Math.random()<.9?2:4};add();add();function render(){grid.innerHTML=a.map(v=>`<div class="merge-cell" data-v="${v}">${v||''}</div>`).join('')};function move(d){const old=a.join(),lines=[];for(let i=0;i<4;i++){let ids=[];for(let j=0;j<4;j++)ids.push(d[0]?(d[0]>0?i*4+3-j:i*4+j):(d[1]>0?(3-j)*4+i:j*4+i));let vals=ids.map(k=>a[k]).filter(Boolean),out=[];for(let j=0;j<vals.length;j++){if(vals[j]===vals[j+1]){out.push(vals[j]*2);setScore(score+vals[j]*2);j++}else out.push(vals[j])}while(out.length<4)out.push(0);ids.forEach((k,j)=>a[k]=out[j])}if(a.join()!==old){add();render()}if(!a.includes(0)&&![0,1,2,3,4,5,6,7,8,9,10,11,12,13,14].some(i=>(i%4<3&&a[i]===a[i+1])||(i<12&&a[i]===a[i+4])))overlay('Ходов нет',`Счёт: ${score}`)}swipes(grid,move);const key=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();move(d)}};addEventListener('keydown',key);render();cleanup=()=>removeEventListener('keydown',key)}
  function memory(){const stage=$('arcadeStage'),grid=document.createElement('div');grid.className='arcade-dom memory-grid';stage.replaceChildren(grid);let cards=[...'🍉🚀🎲🎸🐙🌈⚽👑',...'🍉🚀🎲🎸🐙🌈⚽👑'].sort(()=>Math.random()-.5),open=[],done=new Set(),moves=0;function render(){grid.replaceChildren(...cards.map((v,i)=>{const b=document.createElement('button');b.className=`memory-card ${open.includes(i)||done.has(i)?'open':''}`;b.textContent=open.includes(i)||done.has(i)?v:'?';b.onclick=()=>pick(i);return b}))}function pick(i){if(open.length===2||open.includes(i)||done.has(i))return;open.push(i);render();if(open.length===2){moves++;setScore(moves);if(cards[open[0]]===cards[open[1]]){open.forEach(v=>done.add(v));open=[];render();if(done.size===16)setTimeout(()=>overlay('Все пары найдены!',`Ходов: ${moves}`),250)}else setTimeout(()=>{open=[];render()},650)}}render()}
  function tictac(){const stage=$('arcadeStage'),grid=document.createElement('div');grid.className='arcade-dom tic-grid';stage.replaceChildren(grid);let a=Array(9).fill(''),over=false;const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],win=p=>wins.some(w=>w.every(i=>a[i]===p));function render(){grid.replaceChildren(...a.map((v,i)=>{const b=document.createElement('button');b.className='tic-cell';b.textContent=v;b.onclick=()=>play(i);return b}))}function end(t){over=true;setScore(t==='Победа!'?1:0);setTimeout(()=>overlay(t,t==='Победа!'?'Отличная партия':'Попробуйте ещё раз'),250)}function play(i){if(over||a[i])return;a[i]='✕';if(win('✕')){render();return end('Победа!')}if(a.every(Boolean)){render();return end('Ничья')}let free=a.map((v,i)=>v?null:i).filter(v=>v!=null),pick=free.find(i=>{a[i]='○';const w=win('○');a[i]='';return w})??free.find(i=>{a[i]='✕';const w=win('✕');a[i]='';return w})??(a[4]===''?4:free[Math.floor(Math.random()*free.length)]);a[pick]='○';render();if(win('○'))end('Бот победил')}render()}
  renderWallet();
})();
