(()=>{const tg=window.Telegram?.WebApp,$=id=>document.getElementById(id),API='https://mini-app-omega-roan.vercel.app',list=$('gptMessages'),input=$('gptInput'),send=$('gptSend'),err=$('gptError'),screen=$('gptScreen'),portal=$('portalScreen'),gamesTab=$('gamesTabBtn'),gptTab=$('gptAgentBtn'),createTab=$('createBotTabBtn');let busy=false,last='',failed=null,seen=new Set(),loaded=false;const initData=tg?.initData||'';
function row(m,pending=false){const key=m.id||m.clientMessageId;if(key&&seen.has(key))return;if(key)seen.add(key);const d=document.createElement('div');d.className=`gpt-message ${m.role==='user'?'mine':'assistant'}${pending?' pending':''}`;d.dataset.key=key||'';const p=document.createElement('p');p.textContent=m.content;d.append(p);list.append(d);list.scrollTop=list.scrollHeight}
function showError(t,retry=false){err.classList.remove('hidden');err.replaceChildren(document.createTextNode(t));if(retry){const b=document.createElement('button');b.textContent='Повторить';b.onclick=()=>{err.classList.add('hidden');submit(failed.text,failed.id)};err.append(b)}}
async function history(){if(!initData)return showError('Откройте приложение внутри Telegram');try{const r=await fetch(API+'/api/chat/messages?limit=100'+(last?`&after=${encodeURIComponent(last)}`:''),{headers:{'x-telegram-init-data':initData}}),j=await r.json();if(!r.ok)throw Error(j.error);for(const m of j.messages){row(m);last=m.created_at}err.classList.add('hidden')}catch(e){showError('Не удалось загрузить историю')}}
async function submit(text=input.value.trim(),id=crypto.randomUUID()){if(busy||!text)return;busy=true;send.disabled=true;input.disabled=true;failed={text,id};input.value='';row({role:'user',content:text,clientMessageId:id},true);try{const r=await fetch(API+'/api/chat/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData,message:text,clientMessageId:id})}),j=await r.json();if(!r.ok)throw Error(j.error);row(j.assistantMessage);err.classList.add('hidden');failed=null}catch(e){showError('Сообщение не отправлено. ',true)}finally{busy=false;send.disabled=false;input.disabled=false;input.focus()}}
function hideSections(){['homeScreen','modeScreen','levelScreen','onlineScreen','gameScreen','extraGameScreen','arcadeScreen','gptScreen'].forEach(id=>$(id)?.classList.add('hidden'))}
function showPortal(){hideSections();portal.classList.remove('hidden')}
function openGames(){hideSections();portal.classList.add('hidden');$('homeScreen').classList.remove('hidden')}
function open(){hideSections();portal.classList.add('hidden');screen.classList.remove('hidden');if(!loaded){loaded=true;history()}input.focus()}
gamesTab.onclick=openGames;gptTab.onclick=open;createTab.onclick=()=>{const url='https://t.me/ibraEz';if(tg?.openTelegramLink)tg.openTelegramLink(url);else window.open(url,'_blank','noopener')};$('gptBack').textContent='К разделам';$('gptBack').onclick=showPortal;$('homeBtn').addEventListener('click',showPortal);send.onclick=()=>submit();input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}};if(!new URLSearchParams(location.search).get('room'))showPortal();setInterval(()=>{if(!screen.classList.contains('hidden')&&!busy)history()},3000)})();
